//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceTutor {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTutor.ServicioTutorSoap")]
    public interface ServicioTutorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTutor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarTutor(CapaGUI.ServiceTutor.Tutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTutor", ReplyAction="*")]
        System.Threading.Tasks.Task insertarTutorAsync(CapaGUI.ServiceTutor.Tutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarTutor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarTutor(CapaGUI.ServiceTutor.Tutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarTutor", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarTutorAsync(CapaGUI.ServiceTutor.Tutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarTutor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarTutor(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarTutor", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarTutorAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTutor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarTutor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTutor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarTutorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaTutor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceTutor.Tutor buscaTutor(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaTutor", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceTutor.Tutor> buscaTutorAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionTutor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceTutor.Tutor posicionTutor(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionTutor", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceTutor.Tutor> posicionTutorAsync(int fila);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tutor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string rutField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string correoField;
        
        private string telefonoField;
        
        private string claveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioTutorSoapChannel : CapaGUI.ServiceTutor.ServicioTutorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTutorSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceTutor.ServicioTutorSoap>, CapaGUI.ServiceTutor.ServicioTutorSoap {
        
        public ServicioTutorSoapClient() {
        }
        
        public ServicioTutorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTutorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTutorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTutorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarTutor(CapaGUI.ServiceTutor.Tutor tutor) {
            base.Channel.insertarTutor(tutor);
        }
        
        public System.Threading.Tasks.Task insertarTutorAsync(CapaGUI.ServiceTutor.Tutor tutor) {
            return base.Channel.insertarTutorAsync(tutor);
        }
        
        public void actualizarTutor(CapaGUI.ServiceTutor.Tutor tutor) {
            base.Channel.actualizarTutor(tutor);
        }
        
        public System.Threading.Tasks.Task actualizarTutorAsync(CapaGUI.ServiceTutor.Tutor tutor) {
            return base.Channel.actualizarTutorAsync(tutor);
        }
        
        public void eliminarTutor(string rut) {
            base.Channel.eliminarTutor(rut);
        }
        
        public System.Threading.Tasks.Task eliminarTutorAsync(string rut) {
            return base.Channel.eliminarTutorAsync(rut);
        }
        
        public System.Data.DataSet consultarTutor() {
            return base.Channel.consultarTutor();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarTutorAsync() {
            return base.Channel.consultarTutorAsync();
        }
        
        public CapaGUI.ServiceTutor.Tutor buscaTutor(string rut) {
            return base.Channel.buscaTutor(rut);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceTutor.Tutor> buscaTutorAsync(string rut) {
            return base.Channel.buscaTutorAsync(rut);
        }
        
        public CapaGUI.ServiceTutor.Tutor posicionTutor(int fila) {
            return base.Channel.posicionTutor(fila);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceTutor.Tutor> posicionTutorAsync(int fila) {
            return base.Channel.posicionTutorAsync(fila);
        }
    }
}
