//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceDepartamento {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDepartamento.ServicioDepartamentoSoap")]
    public interface ServicioDepartamentoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDepartamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarDepartamentoService(CapaGUI.ServiceDepartamento.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDepartamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarDepartamentoServiceAsync(CapaGUI.ServiceDepartamento.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDepartamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarDepartamento(CapaGUI.ServiceDepartamento.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarDepartamentoAsync(CapaGUI.ServiceDepartamento.Departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDepartamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarDepartamento(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarDepartamentoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarDepartamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarDepartamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarDepartamentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaDepartamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceDepartamento.Departamento buscaDepartamento(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.Departamento> buscaDepartamentoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionDepartamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceDepartamento.Departamento posicionDepartamento(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.Departamento> posicionDepartamentoAsync(int fila);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Departamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioDepartamentoSoapChannel : CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDepartamentoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap>, CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap {
        
        public ServicioDepartamentoSoapClient() {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarDepartamentoService(CapaGUI.ServiceDepartamento.Departamento departamento) {
            base.Channel.insertarDepartamentoService(departamento);
        }
        
        public System.Threading.Tasks.Task insertarDepartamentoServiceAsync(CapaGUI.ServiceDepartamento.Departamento departamento) {
            return base.Channel.insertarDepartamentoServiceAsync(departamento);
        }
        
        public void actualizarDepartamento(CapaGUI.ServiceDepartamento.Departamento departamento) {
            base.Channel.actualizarDepartamento(departamento);
        }
        
        public System.Threading.Tasks.Task actualizarDepartamentoAsync(CapaGUI.ServiceDepartamento.Departamento departamento) {
            return base.Channel.actualizarDepartamentoAsync(departamento);
        }
        
        public void eliminarDepartamento(int id) {
            base.Channel.eliminarDepartamento(id);
        }
        
        public System.Threading.Tasks.Task eliminarDepartamentoAsync(int id) {
            return base.Channel.eliminarDepartamentoAsync(id);
        }
        
        public System.Data.DataSet consultarDepartamento() {
            return base.Channel.consultarDepartamento();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarDepartamentoAsync() {
            return base.Channel.consultarDepartamentoAsync();
        }
        
        public CapaGUI.ServiceDepartamento.Departamento buscaDepartamento(int id) {
            return base.Channel.buscaDepartamento(id);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.Departamento> buscaDepartamentoAsync(int id) {
            return base.Channel.buscaDepartamentoAsync(id);
        }
        
        public CapaGUI.ServiceDepartamento.Departamento posicionDepartamento(int fila) {
            return base.Channel.posicionDepartamento(fila);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.Departamento> posicionDepartamentoAsync(int fila) {
            return base.Channel.posicionDepartamentoAsync(fila);
        }
    }
}
