//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceDepartamento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Departamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDepartamento.ServicioDepartamentoSoap")]
    public interface ServicioDepartamentoSoap {
        
        // CODEGEN: Generating message contract since element name departamento from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDepartamentoService", ReplyAction="*")]
        CapaGUI.ServiceDepartamento.insertarDepartamentoServiceResponse insertarDepartamentoService(CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDepartamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.insertarDepartamentoServiceResponse> insertarDepartamentoServiceAsync(CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDepartamentoServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDepartamentoService", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequestBody Body;
        
        public insertarDepartamentoServiceRequest() {
        }
        
        public insertarDepartamentoServiceRequest(CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarDepartamentoServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceDepartamento.Departamento departamento;
        
        public insertarDepartamentoServiceRequestBody() {
        }
        
        public insertarDepartamentoServiceRequestBody(CapaGUI.ServiceDepartamento.Departamento departamento) {
            this.departamento = departamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDepartamentoServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDepartamentoServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceDepartamento.insertarDepartamentoServiceResponseBody Body;
        
        public insertarDepartamentoServiceResponse() {
        }
        
        public insertarDepartamentoServiceResponse(CapaGUI.ServiceDepartamento.insertarDepartamentoServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarDepartamentoServiceResponseBody {
        
        public insertarDepartamentoServiceResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioDepartamentoSoapChannel : CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDepartamentoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap>, CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap {
        
        public ServicioDepartamentoSoapClient() {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceDepartamento.insertarDepartamentoServiceResponse CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap.insertarDepartamentoService(CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequest request) {
            return base.Channel.insertarDepartamentoService(request);
        }
        
        public void insertarDepartamentoService(CapaGUI.ServiceDepartamento.Departamento departamento) {
            CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequest inValue = new CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequest();
            inValue.Body = new CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequestBody();
            inValue.Body.departamento = departamento;
            CapaGUI.ServiceDepartamento.insertarDepartamentoServiceResponse retVal = ((CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap)(this)).insertarDepartamentoService(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.insertarDepartamentoServiceResponse> CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap.insertarDepartamentoServiceAsync(CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequest request) {
            return base.Channel.insertarDepartamentoServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.insertarDepartamentoServiceResponse> insertarDepartamentoServiceAsync(CapaGUI.ServiceDepartamento.Departamento departamento) {
            CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequest inValue = new CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequest();
            inValue.Body = new CapaGUI.ServiceDepartamento.insertarDepartamentoServiceRequestBody();
            inValue.Body.departamento = departamento;
            return ((CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap)(this)).insertarDepartamentoServiceAsync(inValue);
        }
    }
}
